name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Sync Openclash stable
      - name: Sync Openclash stable
        run: |
          git clone --depth 1 -b master https://github.com/vernesong/OpenClash.git temp_stable
          rsync -av --delete --exclude='.git' --exclude-from=.syncignore temp_stable/ "Openclash stable/"
          rm -rf temp_stable
          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ ! -z "$line" && ! "$line" =~ ^\s*# ]]; then
              rm -rf "Openclash stable/$line"
            fi
          done < .syncignore
          git add "Openclash stable"
          git commit -m "Sync Openclash stable with upstream master" || echo "No changes to commit"

      # Sync Openclash dev
      - name: Sync Openclash dev
        run: |
          git clone --depth 1 -b dev https://github.com/vernesong/OpenClash.git temp_dev
          rsync -av --delete --exclude='.git' --exclude='.github/workflows/' --exclude-from=.syncignore temp_dev/ "Openclash dev/"
          rm -rf temp_dev
          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ ! -z "$line" && ! "$line" =~ ^\s*# ]]; then
              rm -rf "Openclash dev/$line"
            fi
          done < .syncignore
          git add "Openclash dev"
          git commit -m "Sync Openclash dev with upstream" || echo "No changes to commit"

      # Update luci-app-openclash in Openclash stable
      - name: Update luci-app-openclash in Openclash stable
        run: |
          if [ -d "Openclash stable/luci-app-openclash" ]; then
            rsync -av "Openclash stable/luci-app-openclash/" "Openclash stable/luci-app-openclash/"
            git add "Openclash stable/luci-app-openclash"
            git commit -m "Update luci-app-openclash in Openclash stable" || echo "No changes to commit"
          else
            echo "luci-app-openclash directory not found in Openclash stable"
          fi

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          if [ -f "Openclash stable/luci-app-openclash/Makefile" ]; then
            MAKEFILE_VERSION=$(grep 'PKG_VERSION:=' "Openclash stable/luci-app-openclash/Makefile" | cut -d'=' -f2)
            sed -i "s/versi: .*/versi: $MAKEFILE_VERSION/" README.md
            git add README.md
            git commit -m "Update versi ke $MAKEFILE_VERSION" || echo "No version changes to commit"
            git push origin main
          else
            echo "Makefile not found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
