name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone upstream repository
        run: |
          git clone --depth 1 -b dev https://github.com/vernesong/OpenClash.git upstream

      - name: Copy files from upstream
        run: |
          rsync -av --exclude='.git' --exclude-from=.syncignore upstream/ .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync with upstream dev branch" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          if [ -f luci-app-openclash/Makefile ]; then
            MAKEFILE_VERSION=$(grep 'PKG_VERSION:=' luci-app-openclash/Makefile | cut -d'=' -f2)
            sed -i "s/versi: .*/versi: $MAKEFILE_VERSION/" README.md
            git add README.md
            git commit -m "Update versi ke $MAKEFILE_VERSION" || echo "No version changes to commit"
            git push origin main
          else
            echo "Makefile not found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}